name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Get project version
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Project version is $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Build with Maven
        run: |
          mvn clean package dockerfile:build -DskipTests
      - name: Log in to Ali Container
        run: |
          docker login --username=${{ secrets.ALI_CONTAINER_USER }} --password="${{ secrets.ALI_CONTAINER_PWD }}" registry.cn-hongkong.aliyuncs.com
      - name: Push Docker image to Ali Container
        #  docker push registry.cn-hongkong.aliyuncs.com/runnable-run/kage:${{ env.VERSION }}
        run: |
          docker tag registry.cn-hongkong.aliyuncs.com/runnable-run/kage:${{ env.VERSION }} registry.cn-hongkong.aliyuncs.com/runnable-run/kage:latest
          docker push registry.cn-hongkong.aliyuncs.com/runnable-run/kage:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl
      - name: Set up KUBE_CONFIG
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > K3S_KUBE_CONFIG.yaml
          chmod 600 K3S_KUBE_CONFIG.yaml
      - name: Deploy to K3s
        run: |
          kubectl --kubeconfig=K3S_KUBE_CONFIG.yaml apply -f k3s-deployment-prod.yaml
          kubectl --kubeconfig=K3S_KUBE_CONFIG.yaml patch deployment kage-deployment -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"`date +'%s'`\"}}}}}" -n 996ninja
          
          
